apiVersion: v1
kind: Namespace
metadata:
  name: spike-app

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: spike-app-config
  namespace: spike-app
data:
  APP_ENV: k8s
  SERVICE_NAME_A: spike-app-a
  SERVICE_NAME_B: spike-app-b
  DOWNSTREAM_URL_A: http://spike-app-b-svc:8080
  DOWNSTREAM_URL_B: http://spike-app-a-svc:8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spike-app-a
  namespace: spike-app
spec:
  selector:
    matchLabels:
      app: spike-app-a
  replicas: 2
  template:
    metadata:
      labels:
        app: spike-app-a
    spec:
      containers:
        - name: spike-app
          image: anddd7/spike-app:v1
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: spike-app-config
                  key: APP_ENV
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: spike-app-config
                  key: SERVICE_NAME_A
            - name: DOWNSTREAM_URL
              valueFrom:
                configMapKeyRef:
                  name: spike-app-config
                  key: DOWNSTREAM_URL_A

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spike-app-b
  namespace: spike-app
spec:
  selector:
    matchLabels:
      app: spike-app-b
  replicas: 2
  template:
    metadata:
      labels:
        app: spike-app-b
    spec:
      containers:
        - name: spike-app
          image: anddd7/spike-app:v1
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: spike-app-config
                  key: APP_ENV
            - name: SERVICE_NAME
              valueFrom:
                configMapKeyRef:
                  name: spike-app-config
                  key: SERVICE_NAME_B
            - name: DOWNSTREAM_URL
              valueFrom:
                configMapKeyRef:
                  name: spike-app-config
                  key: DOWNSTREAM_URL_B

---

apiVersion: v1
kind: Service
metadata:
  name: spike-app-a-svc
  namespace: spike-app
spec:
  type: NodePort
  selector:
    app: spike-app-a
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007

---

apiVersion: v1
kind: Service
metadata:
  name: spike-app-b-svc
  namespace: spike-app
spec:
  type: NodePort
  selector:
    app: spike-app-b
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
